# Generated by Django 5.2.10 on 2026-04-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisuggestion',
            name='model_used',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='reasoning_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='reasoning_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
